# Generated by Django 4.1 on 2022-08-29 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='brief_Desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
