# Generated by Django 4.1 on 2022-08-29 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0002_services_brief_desc_alter_services_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
