# Generated by Django 4.1 on 2022-08-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0003_services_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNowForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firtname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
    ]
