# Generated by Django 4.1 on 2022-08-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0006_alter_booknowform_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknowform',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
