# Generated by Django 4.1 on 2022-08-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0007_booknowform_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True)),
                ('lastname', models.CharField(max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=20, null=True)),
                ('phone_no', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
