# Generated by Django 4.1 on 2022-09-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0010_alter_blogs_card_text_alter_blogs_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='card_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
