# Generated by Django 4.1 on 2022-09-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0012_blogs_card_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=50, null=True)),
                ('card_text', models.CharField(max_length=1000, null=True)),
                ('card_link', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
