# Generated by Django 4.1 on 2022-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0014_alter_booknowform_address_alter_booknowform_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='card_title',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='brief_Desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='details',
            field=models.TextField(),
        ),
    ]
