# Generated by Django 4.1 on 2022-09-05 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0015_alter_blogs_card_title_alter_foodcare_card_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='card_link',
            field=models.TextField(default=datetime.datetime(2022, 9, 5, 12, 51, 31, 797876, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='card_text',
            field=models.TextField(default=datetime.datetime(2022, 9, 5, 12, 51, 44, 589195, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='card_title',
            field=models.TextField(default=datetime.datetime(2022, 9, 5, 12, 51, 49, 259362, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booknowform',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booknowform',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_link',
            field=models.TextField(default=datetime.datetime(2022, 9, 5, 12, 51, 54, 850161, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_text',
            field=models.TextField(default=datetime.datetime(2022, 9, 5, 12, 52, 41, 129729, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_title',
            field=models.TextField(default=datetime.datetime(2022, 9, 5, 12, 52, 49, 248423, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='brief_Desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
