# Generated by Django 4.1.1 on 2022-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcareapp', '0016_alter_blogs_card_link_alter_blogs_card_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='card_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='card_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='card_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booknowform',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booknowform',
            name='email_id',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email_id',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='foodcare',
            name='card_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='brief_Desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
